<a href="https://colab.research.google.com/github/wajdalturki/Wajdalturki/blob/main/ML3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing All

In [178]:
%%capture
# STARTER CODE
!pip install category_encoders
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import category_encoders as ce
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import mean_squared_error, mean_absolute_error, accuracy_score, accuracy_score, recall_score, precision_score
df_r = sns.load_dataset("tips").dropna()
df_c = sns.load_dataset("titanic").dropna()
model_r = LinearRegression()
model_c = LogisticRegression()
x_train_r, x_test_r, y_train_r, y_test_r = train_test_split(df_r.drop("total_bill", axis=1), df_r["total_bill"])
x_train_c, x_test_c, y_train_c, y_test_c = train_test_split(df_c.drop(["survived", "alive", "adult_male"], axis=1), df_c["survived"])
pipe_r = make_pipeline(ce.OrdinalEncoder(), StandardScaler(), LinearRegression()).fit(x_train_r, y_train_r)
pipe_c = make_pipeline(ce.OrdinalEncoder(), StandardScaler(), LogisticRegression()).fit(x_train_c, y_train_c)
y_pred_r = pipe_r.predict(x_test_r)
y_pred_c = pipe_c.predict(x_test_c)

## Loading Dataset

In [179]:
# Load data and drop NaN values
df = pd.read_csv("/seattle_weather_1948-2017.csv").dropna()
df

DATE  PRCP  TMAX  TMIN   RAIN
0      1948-01-01  0.47    51    42   True
1      1948-01-02  0.59    45    36   True
2      1948-01-03  0.42    45    35   True
3      1948-01-04  0.31    45    34   True
4      1948-01-05  0.17    45    32   True
...           ...   ...   ...   ...    ...
25546  2017-12-10  0.00    49    34  False
25547  2017-12-11  0.00    49    29  False
25548  2017-12-12  0.00    46    32  False
25549  2017-12-13  0.00    48    34  False
25550  2017-12-14  0.00    50    36  False

[25548 rows x 5 columns]

In [180]:
df['PRCP'].value_counts()

0.00    14648
0.01      933
0.02      707
0.03      493
0.04      428
        ...  
2.49        1
2.18        1
2.20        1
2.70        1
2.95        1
Name: PRCP, Length: 207, dtype: int64

In [181]:
df['PRCP'] = df["PRCP"].map(lambda i: 1 if i==True else 0)
df['PRCP'].value_counts()

0    25539
1        9
Name: PRCP, dtype: int64

In [182]:
#sns.pairplot(df)

In [183]:
df.head()

DATE  PRCP  TMAX  TMIN  RAIN
0  1948-01-01     0    51    42  True
1  1948-01-02     0    45    36  True
2  1948-01-03     0    45    35  True
3  1948-01-04     0    45    34  True
4  1948-01-05     0    45    32  True

In [184]:
df.describe()

PRCP          TMAX          TMIN
count  25548.000000  25548.000000  25548.000000
mean       0.000352     59.543056     44.513387
std        0.018766     12.773265      8.893019
min        0.000000      4.000000      0.000000
25%        0.000000     50.000000     38.000000
50%        0.000000     58.000000     45.000000
75%        0.000000     69.000000     52.000000
max        1.000000    103.000000     71.000000

## Missing Values

In [185]:
# Check Null Values of Rain columns
#df[pd.isnull(df['RAIN'])]
df[pd.isnull(df['RAIN'])]

Empty DataFrame
Columns: [DATE, PRCP, TMAX, TMIN, RAIN]
Index: []

In [186]:
# Check Null Values of PRCP columns
df[pd.isnull(df['PRCP'])]

Empty DataFrame
Columns: [DATE, PRCP, TMAX, TMIN, RAIN]
Index: []

In [187]:
df['PRCP'].mean()

0.0003522780648191639

In [188]:
df["PRCP"].describe()

count    25548.000000
mean         0.000352
std          0.018766
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          1.000000
Name: PRCP, dtype: float64

## prediction Regression RAIN column
### - Precision, Recall 

In [189]:
logre= LogisticRegression()
X=df.drop(['RAIN','DATE'],axis=1) # dropping columns
y=df['RAIN']
y=y.astype('str')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
logre.fit(X_train,y_train) # Fitting Values

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [190]:
y_pred = logre.predict(X_test)

In [203]:
#Don't Forget Importing ((sklearn.metrics import classification_report)) in the first code

# then Print it 
print('Rain Classification:',classification_report(y_test,y_pred))
print('\n')
print('confusion_matrix:\n ',confusion_matrix(y_test,y_pred))
#print('score: ',accuracy_score(y_test,y_pred))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Rain Classification:               precision    recall  f1-score   support

           0       1.00      1.00      1.00      7663
           1       0.00      0.00      0.00         2

    accuracy                           1.00      7665
   macro avg       0.50      0.50      0.50      7665
weighted avg       1.00      1.00      1.00      7665



confusion_matrix:
  [[7663    0]
 [   2    0]]


###accuracy_score

In [ ]:
print('score: ',accuracy_score(y_test,y_pred))

## prediction Regression PRCP column

In [192]:
df["PRCP"].value_counts(normalize=True)

0    0.999648
1    0.000352
Name: PRCP, dtype: float64

In [193]:
training, test = train_test_split(
    df, # data
    train_size = 0.8, # size of the train data
    test_size = 0.2, # size of test data
    random_state = 42

)
training["PRCP"].value_counts(normalize=True)

0    0.999706
1    0.000294
Name: PRCP, dtype: float64

In [194]:
test["PRCP"].value_counts(normalize=True)

0    0.999413
1    0.000587
Name: PRCP, dtype: float64

In [195]:
# Create Validation Set

# Select target column
target = "PRCP"


# Create training and validation sets
X_train, X_val, y_train, y_val,= train_test_split(
    training.drop([target, "DATE"], axis=1), # Df with features
    training[target], # Df with labels
    train_size=0.8,
    test_size=0.2,
    random_state=42
)
X_train.head()

TMAX  TMIN   RAIN
2783     71    47  False
18263    50    37   True
21613    59    46   True
20304    79    53  False
15497    62    52   True

In [196]:
logres= LogisticRegression()
X=df.drop(['PRCP','DATE'],axis=1) # dropping columns
y=df['PRCP']
y=y.astype('str')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
logres.fit(X_train,y_train) # Fitting Values

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [197]:
y_pred = logres.predict(X_test)

In [206]:
#Don't Forget Importing ((sklearn.metrics import classification_report)) in the first code

# then Print (Classification to prediction )
print('PRCP Classification:',classification_report(y_test,y_pred))
print('\n')
print('confusion_matrix:\n ',confusion_matrix(y_test,y_pred))

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


PRCP Classification:               precision    recall  f1-score   support

           0       1.00      1.00      1.00      7663
           1       0.00      0.00      0.00         2

    accuracy                           1.00      7665
   macro avg       0.50      0.50      0.50      7665
weighted avg       1.00      1.00      1.00      7665



confusion_matrix:
  [[7663    0]
 [   2    0]]


**score**

In [207]:
print('score: ',accuracy_score(y_test,y_pred))

score:  0.9997390737116765


In [ ]:
## get average squared error(MSE) by comparing predicted values with real values. 
print('%.2f'%mean_squared_error(y_test, y_pred))

### SSE Cost of prediction Regression PRCP column

### **Mean Squared Error (MSE)**

In [226]:
# Calculation of Mean Squared Error (MSE)
MSE = mean_squared_error(y_test, y_pred)
MSE

0.0002609262883235486

In [199]:
from sklearn.metrics import mean_squared_error
#mean_squared_error(df['PRCP'])

### **Sum Squared Error (SSE)**

In [ ]:
# Calculation of Sum Squared Error(SSE)
SSE = sum((y_test - y_pred)^2)
SSE

###**Mean Absolute Error (MAE)**

In [219]:
#from sklearn.metrics import mean_absolute_error
MAE= mean_absolute_error(y_test, y_pred, multioutput='raw_values')
MAE

array([0.00026093])

### Mean Absolute deviation function

In [225]:
df.mad() # mad() is mean absolute deviation function

PRCP     0.000704
TMAX    10.595231
TMIN     7.340104
dtype: float64